### ISSUE TITLE
ctensr.funcs (and others) : wrong macsyma indentation in EMACS

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its-vault#1]
Hello,

it seems ctensr.funcs (ctensr.lfuncs and ctensr.ofuncs) have a wrong emacs "file type" line.
In the file there's:

`/*-*macsyma-*-*/`

this should be:

`/*-*-macsyma-*-*/`

regards,
Fausto

**Comment by larsbrinkhoff** [comment]
Hello,

In this repository, there are only unmodified files from ITS.  It's a raw material to use for the main ITS repository.

**Comment by TheFausap** [comment]
Sorry!
